animal = input("What is your favorite animal?\n>")
why = input("Why is the " + animal + " your favorite animal?\n>")
color = input("What color is a " + animal + "?\n>")
location = input("Where do " + animal + "s live?\n>")
diet = input("What do " + animal + "s eat?\n>")
print("Your favorite animal is the " + animal + " because " + why + ". It is " + color + ", eats " + diet + ", and lives in " + location + "!")